---
- name: Install required packages
  openbsd_pkg:
    name:
      - packer
      - packer-vmm
    state: present
  become: true

- name: Fetch installation media
  get_url:
    url: https://cdn.openbsd.org/pub/OpenBSD/7.6/amd64/install76.iso
    checksum: sha256:60cba8cb391b50bba8fa10fc768bd0529636f5345d82133c93e22c798d8e5269
    dest: ./install76.iso
    mode: 0644

- name: Configure interfaces
  copy:
    src: hostname.{{ item }}
    dest: /etc/hostname.{{ item }}
    owner: root
    group: wheel
    mode: 0640
  loop:
    - veb0
    - vport0
  become: true
  notify: netstart

- name: Configure vmd
  template:
    src: vm.conf
    dest: /etc/vm.conf
    owner: root
    group: wheel
    mode: 0644
    validate: vmd -nf %s
  become: true
  notify: vmd

- name: Enable vmd
  service:
    name: vmd
    enabled: true
  become: true

- name: Create http directory
  file:
    path: ./http
    state: directory
    mode: 0755

- name: Create INSTALL.amd64
  file:
    path: ./http/INSTALL.amd64
    state: touch
    mode: 0644

- name: Template install.conf
  template:
    src: install.conf
    dest: ./http/install.conf
    mode: 0644

- name: Create site tarball staging directory
  tempfile:
    state: directory
  register: site_dir

- name: Create site tarball directories
  file:
    path: "{{ site_dir.path }}{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ site_dirs }}"
  become: true

- name: Template site tarball files
  template:
    src: "{{ item.src }}"
    dest: "{{ site_dir.path }}{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ site_files }}"
  become: true

- name: Create site tarball
  community.general.archive:
    path: "{{ site_dir.path }}/*"
    dest: ./http/site76.tgz
    mode: 0644
  become: true

- name: Remove site tarball staging directory
  file:
    path: "{{ site_dir.path }}"
    state: absent
  become: true

- name: Generate index.txt content
  command:
    cmd: ls -l ./http
    strip_empty_ends: false
  register: ls_out
  changed_when: false
  check_mode: false

- name: Create index.txt
  copy:
    dest: ./http/index.txt
    content: "{{ ls_out.stdout }}"
    mode: 0644
